### ISSUE TITLE
accumulate coverage across two different Ruby runs

### ISSUE THREAD

**Issue by Nowaker** [codeclimate/ruby-test-reporter#35]
EDIT: Issue edited. See https://github.com/codeclimate/ruby-test-reporter/issues/35#issuecomment-43269295.

Note: this is not #32.

```
Finished in 0.00044 seconds
2 examples, 0 failures
Coverage = 100.0%. Code Climate encountered an exception: CodeClimate::TestReporter::InvalidPayload
No source files were found in the test report payload
```

It's neither Rails app, nor a gem. Just a very small Ruby command-line app that consists of some files in `lib/` and `bin/` directories. How do I make Code Climate test reporter see these files?

**Comment by bhfailor** [comment]
Thanks to those who make this gem available.

Regarding this issue, for what it is worth, I was testing a [rails app](https://github.com/bhfailor/rundowner) with automated browser testing so I had
```
  gem 'minitest-rails-capybara'
```
in my ```Gemfile``` and
```
require 'minitest/rails/capybara'
```
in ```test/test_helper.rb```
Then I started a [rails API](https://github.com/bhfailor/scrutinizer) and removed those two lines since browser automation was not needed.  But I started getting the error message
```
Coverage = 100.0%. Code Climate encountered an exception: CodeClimate::TestReporter::InvalidPayload
No source files were found in the test report payload
/home/runner/scrutinizer/vendor/bundle/ruby/2.2.0/gems/codeclimate-test-reporter-0.4.7/lib/code_climate/test_reporter/payload_validator.rb:18:in `validate'
/home/runner/scrutinizer/vendor/bundle/ruby/2.2.0/gems/codeclimate-test-reporter-0.4.7/lib/code_climate/test_reporter/payload_validator.rb:11:in `validate'
/home/runner/scrutinizer/vendor/bundle/ruby/2.2.0/gems/codeclimate-test-reporter-0.4.7/lib/code_climate/test_reporter/formatter.rb:21:in `format'
/home/runner/scrutinizer/vendor/bundle/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/result.rb:46:in `format!'
/home/runner/scrutinizer/vendor/bundle/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/configuration.rb:159:in `block in at_exit'
/home/runner/scrutinizer/vendor/bundle/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `call'
/home/runner/scrutinizer/vendor/bundle/ruby/2.2.0/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:60:in `block in <top (required)>'
Started with run options --seed 64965
```
After putting the two lines back in error message went away:
```
Coverage = 100.0%. Sending report to https://codeclimate.com for branch api-authenication... done.
```

**Comment by pbrisbin** [comment]
I've created a new Issue to consolidate this with the 2 other similar issues. Please continue discussion there.
