### ISSUE TITLE
 CodeClimate::TestReporter::InvalidPayload on Rails dummy app

### ISSUE THREAD

**Issue by antek-drzewiecki** [codeclimate/ruby-test-reporter#64]
Hi,

I am using CodeClimate to test my gem with that contains a rails dummy app in my spec/ directory.
Since CodeClimate version 0.4.4 my specs exit with an CodeClimate::TestReporter::InvalidPayload 'A git commit timestamp was not found in the test report payload' error.

#### Stacktrace
```
fatal: Not a git repository: 'dir/wine_bouncer/spec/dummy/.git'
Code Climate encountered an exception: CodeClimate::TestReporter::InvalidPayload
A git commit timestamp was not found in the test report payload
rvmgemdir/codeclimate-test-reporter-0.4.4/lib/code_climate/test_reporter/payload_validator.rb:16:in `validate'
rvmgemdir/codeclimate-test-reporter-0.4.4/lib/code_climate/test_reporter/payload_validator.rb:11:in `validate'
rvmgemdir/codeclimate-test-reporter-0.4.4/lib/code_climate/test_reporter/formatter.rb:21:in `format'
rvmgemdir/simplecov-0.9.1/lib/simplecov/result.rb:46:in `format!'
rvmgemdir/simplecov-0.9.1/lib/simplecov/configuration.rb:158:in `block in at_exit'
rvmgemdir/simplecov-0.9.1/lib/simplecov/defaults.rb:54:in `call'
rvmgemdir/simplecov-0.9.1/lib/simplecov/defaults.rb:54:in `block in <top (required)>'
```

#### What is probably happening
I have a gem git repository on ```dir/wine_bouncer/.git``` and an dummy app on ```dir/wine_bouncer/spec/dummy/.git```. I am running my specs from the gem root directory. Since my specs use a mounted dummy app for integration testing, ```ruby-test-preporter``` assumes the .git directory is inside the specs directory.

This is probably because the Rails module is defined upon exiting. And is probably introduced by the #63 PR on the ```git_dir``` method.

This issue both occurs on Travis-ci and console when having a dummy app mounted in your gem.

**Comment by antek-drzewiecki** [comment]
@Strech do you have any idea how we can fix this issue so both solutions will work?
I don't think checking if the Rails.root output contains specs directory is the right way to go.

**Comment by antek-drzewiecki** [comment]
Will changing Rails.root to Dir.pwd solve the issue?

**Comment by Strech** [comment]
@antek-drzewiecki in my case Dir.pwd return /tmp/ folder. I think we can try to find out place of .git, looking for popular places, like pwd and rails root

**Comment by craiglittle** [comment]
Hey there!

FWIW, I'm experiencing the same issue for what appears to be similar reasons. Looks like [there are others out there](http://stackoverflow.com/questions/27787179/codeclimate-coverage-error-fatal-not-a-git-repository-this-is-a-git-reposito) as well.

**Comment by calavera** [comment]
oh, this is interesting. So, `Rails` is defined, but it's for the app that you're using as a stub. We might need to pre calculate the path to the git directory before we do any of these calls.

**Comment by Strech** [comment]
@calavera I can add `.git` directory existing checks, before select concrete folder

**Comment by NullVoxPopuli** [comment]
Is there a version of ruby-test-reporter that doesn't have this problem? I'd like to have coverage tracked for my gem: https://github.com/NullVoxPopuli/authorizable :-)

**Comment by calavera** [comment]
@NullVoxPopuli yeah, you can point your Gemfile to the previous version while we investigate this:

https://rubygems.org/gems/codeclimate-test-reporter/versions/0.4.3

**Comment by NullVoxPopuli** [comment]
thanks!

**Comment by calavera** [comment]
I just opened #65 with a fix. @antek-drzewiecki, @craiglittle, @NullVoxPopuli do you mind to test that the change fixes your issue? It should be a small change in your Gemfile until it's merged and released:

```ruby
gem "codeclimate-test-reporter", git: "https://github.com/codeclimate/ruby-test-reporter.git", branch: "check_git_dir"
```

**Comment by Strech** [comment]
@calavera For my case your branch says `Sending report to https://codeclimate.com for branch master... done.` So, this solve my problem too :+1:

**Comment by calavera** [comment]
cool, I'm going to wait for some other confirmation before merging, but expect a new release tomorrow morning. :tada:

**Comment by NullVoxPopuli** [comment]
@calavera my results:

from bundle install:
    Using codeclimate-test-reporter 0.4.4 (was 0.4.3) from https://github.com/codeclimate/ruby-test-reporter.git (at check_git_dir)

after running rspec:

    Coverage = 89.71%. fatal: Not a git repository: '/home/me/Development/authorizable/spec/support/rails_app/.git'
    fatal: Not a git repository: '/home/me/Development/authorizable/spec/support/rails_app/.git'
    fatal: Not a git repository: '/home/me/Development/authorizable/spec/support/rails_app/.git'


Gemfile:

    source 'https://rubygems.org'
    
    # Specify your gem's dependencies in authorizable.gemspec
    gemspec
    
    gem "codeclimate-test-reporter", git: "https://github.com/codeclimate/ruby-test-reporter.git", branch: "check_git_dir"

**Comment by calavera** [comment]
thanks @NullVoxPopuli. I'm cloning your gem to reproduce the issue.

**Comment by calavera** [comment]
`0.4.5` is up in rubygems.org with #65 and #66 in it. Thank you all for helping with this.

**Comment by craiglittle** [comment]
Thanks, David!

**Comment by markoudev** [comment]
Am I missing something why 0.4.5 does not fix this for me? :sob: 

```
...

Installing codeclimate-test-reporter 0.4.5

...

Coverage = 95.35%. fatal: Not a git repository: '/.git'
fatal: Not a git repository: '/.git'
fatal: Not a git repository: '/.git'
Code Climate encountered an exception: CodeClimate::TestReporter::InvalidPayload
A git commit timestamp was not found in the test report payload
/home/travis/.rvm/gems/ruby-2.2.0/gems/codeclimate-test-reporter-0.4.5/lib/code_climate/test_reporter/payload_validator.rb:16:in `validate'
/home/travis/.rvm/gems/ruby-2.2.0/gems/codeclimate-test-reporter-0.4.5/lib/code_climate/test_reporter/payload_validator.rb:11:in `validate'
/home/travis/.rvm/gems/ruby-2.2.0/gems/codeclimate-test-reporter-0.4.5/lib/code_climate/test_reporter/formatter.rb:21:in `format'
/home/travis/.rvm/gems/ruby-2.2.0/gems/simplecov-0.9.1/lib/simplecov/result.rb:46:in `format!'
/home/travis/.rvm/gems/ruby-2.2.0/gems/simplecov-0.9.1/lib/simplecov/configuration.rb:158:in `block in at_exit'
/home/travis/.rvm/gems/ruby-2.2.0/gems/simplecov-0.9.1/lib/simplecov/defaults.rb:54:in `call'
/home/travis/.rvm/gems/ruby-2.2.0/gems/simplecov-0.9.1/lib/simplecov/defaults.rb:54:in `block in <top (required)>'
```

**Comment by markoudev** [comment]
Fixed it. Good thing @antek-drzewiecki works for the same company :wink: 

In my `test_helper.rb` I include `rails/all` since my gem is meant for Rails apps and I want to use some Rails magic. However, during tests there isn't a Rails app, but `Rails` is defined. Hence, `git_dir` in `git.rb` returns an empty string rather than `.` or the actual Rails root.

I don't want to start a Rails app during my tests, so in `test_helper.rb` I added:

```ruby
CodeClimate::TestReporter.configuration.git_dir = "."
```

Now reporting to CodeClimate!

**Comment by Strech** [comment]
@markoudev As you can see here:

```
        def git_dir
          return CodeClimate::TestReporter.configuration.git_dir unless CodeClimate::TestReporter.configuration.git_dir.nil?

          root = "."

          if defined?(Rails) && File.directory?(File.expand_path(".git", Rails.root))
            root = Rails.root
          end

          root
        end
```

Even if you not define you `git_dir`, its return `'.'`, because you haven't `Rails.root/.git` dir, nope?

**Comment by antek-drzewiecki** [comment]
@Strech , not quite. 
When you `require 'rails/all'` in a non Rails project `Rails` is defined as a constant and `Rails.root` returns `nil`. So when you run the rspec in your project that has a .git folder, the git_root is first defined as `"."`. Because Rails is a constant and Rails.root returns nil `File.expand_path(".git", Rails.root)` will return your current working directory + .git (expand_path with second argument nil will point to your current directory). So both arguments are true If a .git folder exists in it and the root variable will be declared as `nil`.

Then when you run a command for example `git("log -1 --pretty=format:'%H'")`, the real console output will be:  `git --git-dir=/.git log -1 --pretty=format:'%H`. Where --git-dir is the Filesystem root directory.

**Comment by Strech** [comment]
@antek-drzewiecki May be  we should check `Rails.root` because `nil`, is not correct value for root directory?

**Comment by antek-drzewiecki** [comment]
Thats exactly what I'm doing there. Checking if Rails.root does not return nil.
Nil is indeed not a correct return value of the method git_dir, because it will look for a git directory in your Filesystem root.

**Comment by Strech** [comment]
@calavera Looks like we should add something like this https://github.com/codeclimate/ruby-test-reporter/issues/64#issuecomment-70082151 to fix missed git directory completely?

**Comment by antek-drzewiecki** [comment]
Ill add a pull request. And try to add specs while I'm at it.

**Comment by Strech** [comment]
@antek-drzewiecki Sounds great :+1:

**Comment by calavera** [comment]
sorry for the late reply, I was on vacation. That sounds like a good idea, please go ahead with that PR. I'll merge it asap

**Comment by Strech** [comment]
@antek-drzewiecki plz look https://github.com/codeclimate/ruby-test-reporter/pull/69

**Comment by acook** [comment]
I'm seeing a recurrence of this issue when using Travis CI. It's not a Rails project, it's a gem with no runtime dependencies or weird directories, just `lib` and `spec` as should be expected.

Here's the error (also on [Travis](https://travis-ci.org/acook/config_module/jobs/83412099)):

~~~
Coverage = 96.08%. fatal: Not a git repository: '/home/travis/build/acook/config_module
/.git'
fatal: Not a git repository: '/home/travis/build/acook/config_module
/.git'
fatal: Not a git repository: '/home/travis/build/acook/config_module
/.git'
Code Climate encountered an exception: CodeClimate::TestReporter::InvalidPayload
A git commit timestamp was not found in the test report payload
~~~

I was able to hack around the problem like this, but it seems like it should be really unnecessary:

~~~ruby
  CodeClimate::TestReporter.configure do |config|
    config.git_dir = `git rev-parse --show-toplevel`.strip
  end
~~~

**Comment by aaronmallen** [comment]
I am also having this issue and like @acook I am using it for a ruby gem so no rails... I seem to only see the issue if I add filters to simplecov, ie:
```
SimpleCov.start do
  add_filter 'spec'
end
```
