### ISSUE TITLE
Working directories containing a space in the name cause an exception

### ISSUE THREAD

**Issue by bklang** [codeclimate/ruby-test-reporter#70]
This exception showed up in our CI logs:

```
git: 'Master/workspace/.git' is not a git command. See 'git --help'.
git: 'Master/workspace/.git' is not a git command. See 'git --help'.
git: 'Master/workspace/.git' is not a git command. See 'git --help'.
Code Climate encountered an exception: CodeClimate::TestReporter::InvalidPayload
A git commit timestamp was not found in the test report payload
/var/lib/jenkins/.gem/ruby/2.0.0/gems/codeclimate-test-reporter-0.4.5/lib/code_climate/test_reporter/payload_validator.rb:16:in `validate'
/var/lib/jenkins/.gem/ruby/2.0.0/gems/codeclimate-test-reporter-0.4.5/lib/code_climate/test_reporter/payload_validator.rb:11:in `validate'
/var/lib/jenkins/.gem/ruby/2.0.0/gems/codeclimate-test-reporter-0.4.5/lib/code_climate/test_reporter/formatter.rb:21:in `format'
/var/lib/jenkins/.gem/ruby/2.0.0/gems/simplecov-0.9.0/lib/simplecov/result.rb:46:in `format!'
/var/lib/jenkins/.gem/ruby/2.0.0/gems/simplecov-0.9.0/lib/simplecov/configuration.rb:158:in `block in at_exit'
/var/lib/jenkins/.gem/ruby/2.0.0/gems/simplecov-0.9.0/lib/simplecov/defaults.rb:54:in `call'
/var/lib/jenkins/.gem/ruby/2.0.0/gems/simplecov-0.9.0/lib/simplecov/defaults.rb:54:in `block in <top (required)>'
```

The cause was determined to be a space in the path leading to the directory.  We temporarily worked around this by specifying a relative path in the config, but I imagine this will bite others.

**Comment by calavera** [comment]
Oh, this is very unfortunate, thanks for reporting it. It should be easy to fix if you want to go ahead, the directory in https://github.com/codeclimate/ruby-test-reporter/blob/master/lib/code_climate/test_reporter/git.rb#L48 should be quoted.

Otherwise, I'll submit a patch :soon:

**Comment by dblandin** [comment]
Looks like this was addressed in https://github.com/codeclimate/ruby-test-reporter/pull/71. I'm going to go ahead and close this issue. Thanks!
